[pytest]
norecursedirs = data .tox .idea node_modules ~*
pythonpath = src
testpaths = tests
python_files = test_*.py
addopts = -rs
          -vv
          --tb=short
filterwarnings =
    ignore::DeprecationWarning
    ignore::pytest.PytestConfigWarning
