[pytest]
norecursedirs = data .tox .idea node_modules ~*
pythonpath = src
testpaths = tests
python_files = test_*.py
addopts = -rs
          -vv
          --tb=short
          --cov=ihela_client
          --cov-report=term-missing
          --cov-report=xml
          --cov-report=html
filterwarnings =
    ignore::DeprecationWarning
    ignore::pytest.PytestConfigWarning
