[tox]
requires =
    tox>=4.2
    tox-uv>=1.25
env_list =
    lint
    d52
    d60
    docs
    pkg_meta
    typecheck

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:d52]
description = run tests with Django 5.2
allowlist_externals = pytest
deps =
    django>=5.2,<6.0
    pytest>=8.0.0
    pytest-cov>=4.1.0
set_env =
    PYTHONDONTWRITEBYTECODE = 1
    PYTHONPATH = {toxinidir}/src
commands =
    pytest {posargs:tests -vv}

[testenv:d60]
description = run tests with Django 6.0
allowlist_externals = pytest
deps =
    django>=6.0a1
    pytest>=8.0.0
    pytest-cov>=4.1.0
set_env =
    PYTHONDONTWRITEBYTECODE = 1
    PYTHONPATH = {toxinidir}/src
commands =
    pytest {posargs:tests -vv}

[testenv:typecheck]
description = run mypy type checker
skip_install = true
deps =
    mypy>=1.0
set_env =
    MYPYPATH = src
commands =
    mypy src/

[testenv:docs]
description = build mkdocs documentation
skip_install = false
extras =
    docs
commands =
    mkdocs build {posargs:}

[testenv:pkg_meta]
description = check python package metadata
skip_install = true
deps =
    twine>=5.1.1
    uv>=0.5
commands =
    {envpython} -m uv build -q --sdist --wheel --out-dir {env_tmp_dir} .
    {envpython} -m twine check {env_tmp_dir}{/}*
